### ISSUE TITLE
Use domain ID instead of domain name when bootstrapping keystone

### ISSUE THREAD

**Issue by lbragstad** [lbragstad/keystone-performance#16]
The `bootstrap.py` script uses the keystone client to bootstrap the new keystone deployment. It recently started failing with: 

```
Exception in thread Thread-100:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bootstrap.py", line 45, in create_projects
    name=uuid.uuid4().hex)
  File "/usr/local/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v3/projects.py", line 97, in create
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 74, in func
    return f(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 342, in create
    self.key)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 173, in _post
    resp, body = self.client.post(url, body=body, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 193, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 344, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 112, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/session.py", line 419, in request
    raise exceptions.from_response(resp, method, url)
BadRequest: Could not find domain: Default (HTTP 400) (Request-ID: req-bb472e0d-5822-47ed-a071-0c11af38e0d3)
```

We should be using the domain ID instead of the name.

**Comment by lbragstad** [comment]
Fixed with https://github.com/lbragstad/keystone-performance/commit/052f17621d839e5202c3bddd19e5d0c5cfaca971
